package middleware.impl.tcp.requests;

/**
 * Created by jpoisson on 2017-09-28.
 */
public enum MiddlewareTCPRequestTypes {
    ADD_FLIGHTS_REQUEST,
    ADD_CARS_REQUEST,
    ADD_ROOMS_REQUEST,
    ADD_CUSTOMER_REQUEST,
    ADD_CUSTOMER_WITH_ID_REQUEST,
    DELETE_FLIGHT_REQUEST,
    DELETE_CAR_REQUEST,
    DELETE_ROOM_REQUEST,
    DELETE_CUSTOMER_REQUEST,
    QUERY_FLIGHT_REQUEST,
    QUERY_CAR_REQUEST,
    QUERY_ROOM_REQUEST,
    QUERY_CUSTOMER_INFO_REQUEST,
    QUERY_FLIGHT_PRICE_REQUEST,
    QUERY_CAR_PRICE_REQUEST,
    QUERY_ROOM_PRICE_REQUEST,
    RESERVE_FLIGHT_REQUEST,
    RESERVE_CAR_REQUEST,
    RESERVE_ROOM_REQUEST,
    ITINERARY_REQUEST
}
